### PR TITLE
Added DHCP configuration support

### PR DESCRIPTION
**Pull request by BrainStone**
Now you can configure the DHCP support

### CODE REVIEW

**Comment by r-pufky** [comment]
Thanks for all the pull requests for pihole, I really appreciate it! These are now merged into the latest release, will be publish on galaxy shortly.

I did swap to using FQCN names for ipaddr/nthhost -- in specific configurations non-FQCN will fail being unable to resolve the method name.

**Comment by BrainStone** [comment]
My pleasure to help out ^^

One note, you need to click the import button on the list of your contributions for Galaxy to sync with the GitHub tags.

**Comment by BrainStone** [comment]
Funnily enough the FQCN names did not work for me. Ansible could not resolve them.  
I guess the Ansible version in my WSL is really outdated... though it's absolutely fair to use the ambiguity free names.

**Comment by r-pufky** [comment]
Let me know what Ansible version you are using, anything above 2.11 should work with FQCN; though I don't use WSL so there might be a weird interaction there that may need to be addressed.

```bash
$ ansible --version
ansible [core 2.12.1]
  config file = /home/{redacted}/git/srv/cfg/ansible/ansible.cfg
  configured module search path = ['/home/{redacted}/git/srv/cfg/ansible/.ansible/working/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/{redacted}/git/srv/cfg/ansible/.ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/{redacted}/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/{redacted}/git/srv/cfg/ansible/.ansible/bin/ansible
  python version = 3.10.6 (main, Aug  3 2022, 17:39:45) [GCC 12.1.1 20220730]
  jinja version = 3.0.3
  libyaml = True
```

**Comment by BrainStone** [comment]
Yeah it was just my installation being outdated. All good

**Pull request merged**
